apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-bt
  namespace: media
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: qbittorrent
  ports:
    - name: bt-tcp
      protocol: TCP
      port: 30881
      targetPort: 30881
      nodePort: 30881
    - name: bt-udp
      protocol: UDP
      port: 30881
      targetPort: 30881
      nodePort: 30881
