crds:
  install: true

server:
  service:
    type: ClusterIP

configs:
  params:
    server.insecure: false
  cm:
    kustomize.buildOptions: "--enable-alpha-features --enable-helm --load-restrictor LoadRestrictionsRootOnly"
    application.instanceLabelKey: "app.kubernetes.io/instance"
