crds:
  install: true

server:
  service:
    type: ClusterIP

configs:
  params:
    server.insecure: false
  cm:
    kustomize.buildOptions: "--enable-alpha-features --enable-alpha-plugins --enable-exec --enable-helm --load-restrictor LoadRestrictionsRootOnly"
    application.instanceLabelKey: "app.kubernetes.io/instance"

  repo:
    env:
    - name: XDG_CONFIG_HOME
      value: /.config
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/keys.txt
    initContainers:
    - args:
      - echo "Installing KSOPS..."; mv ksops /custom-tools/; mv kustomize /custom-tools/;
        echo "Done.";
      command:
      - /bin/sh
      - -c
      image: viaductoss/ksops:v4.4.0
      name: install-ksops
      volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
    volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /.config/sops/age
      name: sops-age
    volumes:
    - emptyDir: {}
      name: custom-tools
    - name: sops-age
      secret:
