creation_rules:
  - path_regex: '\.sops\.yaml$'
    key_groups:
      - age:
          - 'age1v5xqeh0yg2qp2adtje8crzrut467mrsjnh4cax7cu8xghrnvm54qg0fyde'
  - unencrypted_regex: '^(apiVersion|metadata|kind|type)$'
    key_groups:
      - age:
          - 'age1v5xqeh0yg2qp2adtje8crzrut467mrsjnh4cax7cu8xghrnvm54qg0fyde'
