creation_rules:
  - path_regex: '\.sops\.yaml$'
    key_groups:
      - age:
          - "age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev"
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          - "age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev"
