extends: default

rules:
  document-start: disable
  truthy: disable
  line-length:
    max: 140
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
ignore: |
  argocd/base/cert-manager/issuers/secret-cf-token.yaml
  argocd/base/democratic-csi/secrets/truenas-api-key.yaml
  argocd/base/pocket-id/secrets/pocket-id-secret.yaml
  argocd/base/pocket-id/secrets/forward-auth-secret.yaml
  argocd/base/plex/secrets/plex-secret.yaml
  argocd/base/mixarr/secrets/mixarr-secret.yaml
  argocd/base/traefik-forward-auth/secrets/forward-auth-secret.yaml
  talos/prod/talsecret.sops.yaml
