apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - ../../base/monitoring

helmCharts:
  - name: kube-prometheus-stack
    namespace: monitoring
    releaseName: kps
    repo: https://prometheus-community.github.io/helm-charts
    version: 85.4.0
    valuesFile: values-kube-prometheus-stack.yaml
    includeCRDs: true
  - name: loki
    namespace: monitoring
    releaseName: loki
    repo: https://grafana.github.io/helm-charts
    version: 7.0.0
    valuesFile: values-loki.yaml
    includeCRDs: true
  - name: promtail
    namespace: monitoring
    releaseName: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.17.1
    valuesFile: values-promtail.yaml
    includeCRDs: true
