crds:
  enabled: true

defaultRules:
  create: true

alertmanager:
  enabled: true
  ingress:
    enabled: false
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

grafana:
  enabled: true
  adminPassword: changeme
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: Europe/Paris
  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      jsonData:
        timeout: 60
        maxLines: 1000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP

prometheus:
  enabled: true
  ingress:
    enabled: false
  prometheusSpec:
    replicas: 1
    retention: 30d
    retentionSize: "45GB"
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi

prometheusOperator:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  admissionWebhooks:
    patch:
      enabled: true

kubeApiServer:
  enabled: true
kubelet:
  enabled: true
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
coreDns:
  enabled: true

nodeExporter:
  enabled: true
kube-state-metrics:
  enabled: true
