apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: radarr
          image: ghcr.io/hotio/radarr:release
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7878
          livenessProbe:
            httpGet:
              path: /
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Paris"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: radarr-pvc
              mountPath: /config
            - name: media-pvc
              mountPath: /media
            - name: download-pvc
              mountPath: /downloads
      volumes:
        - name: radarr-pvc
          persistentVolumeClaim:
            claimName: radarr-pvc
        - name: media-pvc
          persistentVolumeClaim:
            claimName: media-pvc
        - name: download-pvc
          persistentVolumeClaim:
            claimName: download-pvc
