apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-key
    namespace: democratic-csi
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:Lzm8Ic2lO3eZIKi33oaoNL4XXFJXKmdP8uHuWMef6mjpXhtqWP3efjnkjyjrXnn4od9FGVfvN4L1Ghqs+b8tKs/I,iv:jG/AgVzsi8Y3Si6RaCOpJrKeps63EDqluJZOX8DnTE0=,tag:2U0acrg2rJYg3OK7YGNuMw==,type:str]
sops:
    age:
        - recipient: age1tfhrx9u62qypvelr5padylmf3es8fc5qzlkg4y6qf266637sgs7sem52p9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZUtTdnlabzdaQjh2elJD
            Z2ZyMzZsclZoZmtSMnl1NDBLbjJFRi9vRWcwCkhXSXlMVEhHWlh1eXJ4NzdJOXh5
            THE0d0NMTHVQVm9BNHdsYVFDeW45RDgKLS0tIENpQTFocEc2bjd5Yi9weXVBRGp6
            RzlXVzlCczFONkZmWXRjNG1BOEtzUVUKMniG5RNXVGFRny0AsVnnppJUeVRZ2Pe7
            vAXP+jWFeob92cs/vBDFDKlJ4IM+vG/CZ48FenR9NCvfdFaUNsmujQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T09:34:03Z"
    mac: ENC[AES256_GCM,data:+ZsiZZJMGx0ScX9yX5n6Q/3BsNOC9WWLhUezuqDJpwUck6EnQjLbHutJYle9rpumSvnTrmrjoJYu2ejKoB/JxjPGUN63burNLaKSiGCZSkBgGLxr8nCUxNny0zhKQPk9MzZhTso4f0IHXJVnXfC0n+8LFuLLq+/pZXKXaGW5vdM=,iv:xkS0C1aEoTw1rgOfVGlteyuUzmxbHlSfRVsWhVD55Qw=,tag:MdTMLeO+HWejvSseoUhExw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
