apiVersion: v1
kind: Secret
metadata:
  name: truenas-csi-driver-config
  namespace: democratic-csi
type: Opaque
stringData:
  driver-config-file.yaml: |
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 192.168.1.5
      port: 80
      apiKey: "<TrueNAS API key: Credentials > API Keys > Add>"
      allowInsecure: true
    sshConnection:
      host: 192.168.1.5
      port: 22
      username: root
      password: ""
      privateKey: ""
    zfs:
      datasetParentName: applications/dev
      detachedSnapshotsDatasetParentName: applications/dev-snapshots
      datasetProperties:
        "org.freenas:description": ""
      datasetEnableQuotas: true
      datasetEnableReservation: false
    nfs:
      shareHost: 192.168.1.5
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: root
      shareMapallUser: ""
      shareMapallGroup: ""
