apiVersion: v1
kind: Secret
metadata:
    name: truenas-csi-driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:WmJzb3Ahj4feg5SI+sbtE1yuMzoq3dsxAQQB3X5o/GxwWVzcCrc3UvWdjfdk7Pl6dTMybrAjhfiHQGphUl07EU4S822Ofw3VcpZQYDNWMlULF6gBdRIp9Gn8fOLdE67e5JrcYhkhOPei2KHpFjP0zYHnvx/QulKEfRv/6VdQvHjtJbNUue41K/aqrQvVdFDqzImGkiRdurTI/9j5ZsXMRrpErcPXWCAcEh3E5iBL1Mphvv6CxJJPE947UAryasdfGz1GqpwB1YhCyIDMXPDLqy1Qn7UxXl+B9UKB0k+mpTvrOUmiZlISpV2C0ouC/d6abyq3KE8YbQNXFELpLg2pvqvDB9QRsJofGMlo8oLkSJMYmzlBHpdA/tjxGt8NPRcXlmaLTLX5Tlln8s9dfpZHQ+fkyRqiNs6eGW5hIqxxhCIN56X9e1hfV7ggALp9miKmQjO+kqwXq5yoUhfBAxMcKnBebRa028ue1YulolLdpHbja/D+Xl1S7WxrEV6gxXQgZ9Zt4kLZjGyGdNq1hjwX7NqF2O7ASsfCuCVsTwig/ILkt+zH34Y7Ga1F9GTapAuUC22KZ3xKHBNytwzfydeoAGzr8LKQAkcPCEufIYiAVa3Z6AiVol0BAwJEXLMw7ReqRaIuvVHQZq1/3tRhV5+yC2rg6mFQEAnsuDctyD1bzuSXrnMGCrA3sQEZFwTg8zQ06yOQObNdd8J34kX1f7qB4Jy7lUqlLhYSvJcIcwxkGEyLv9fvI7yeX0I/OyfVHRF+8Wtx/f2R2O07YI4DTzitoFXymHnv5NiQkK+LyVBir3bk1Woc3FEo1wcyROhN8kHZ3J8=,iv:gv8uLTs8vD3clbfzlatjOS+2KqS0VCgWPTK8MEeJTXw=,tag:9IRD2sbP1vRnWqyJMlZ8DA==,type:str]
sops:
    age:
        - recipient: age1tfhrx9u62qypvelr5padylmf3es8fc5qzlkg4y6qf266637sgs7sem52p9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR2l5OTd2RE1DRzFYaTFv
            eG5UR2lOQ0hMMUZ6Sko4NW96ekMvbmV3Ym5BClArbVNHcXFxTlIrQ1ArODNjY2cv
            bDArR3ZlVGtBNk9HN2dOK2NBRGFkbWsKLS0tIHRDSDdXU1pvZ29SY1N4Q1UrQmhO
            bGR1Ym5BOHY2ZjFzY2U2M0hRNkd3bjgKuA6WzYmspIt21Y9FjI63OfatUBHojdLz
            +Yzq/PAf9idnl9RpvOSimhkRezswZ3zgHyfCzEZev4ExXVrygOWTRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T11:45:11Z"
    mac: ENC[AES256_GCM,data:GzMOk6+kLbeJQyBRfGR2G7C+4Qe9hiQEHE96SOut9XX9jBxrVh3PSjYHnss4wT87481OsGgu5GbKh/JczcyGQv3WPZ0+6DNgQVLxbtNOtOzP1J0TM5GJ0kHqqHFkVHX+Ety7i9fmaooU1zKLuRAXtYoneSJBigbhELbIWEyjWlY=,iv:/DNTBJgohK27qkOKKmpfvTv868EXtRBDhkWkHfNLNF8=,tag:h9oEbFx8BcOoepCy22Jo9Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
