apiVersion: v1
kind: Secret
metadata:
    name: truenas-csi-driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:k40imTaBfiao5xi8fVDZ2W+ORXhKR5DrwcDcNs6PgOv2+AcIRC4HBIlkj+Xscy/iW9ZMXK0rZf5jqLxbkOkbm2+Dbqg1VfxyVGp2ETCxghRpr+HQihfRkxjW3LWLtX+tWL+W0OsNMiZ8L/orGRuqlFua/FXIxVbJY1QVsbOce1ZvdYA+rBzxAaLSJG7sMNo2CWMQtHyte3uX3TPHdJC8zyU77H1yW5uI45zsnNPFeNq4kcCqKFiKco3sAMTaPDc359+nbbZnmL7NRgwKYLatyiBWTqc3WlXomjCDYddRJHkSm2V4Bm6eUVB19KRkKmQrtUgA3B2alzT3qBaUlBx5WfEEQnFq9JLBMwUMyOQmJu7bbbsrji1p7pB9WyR4zmhbfmMXzZaAMwGINxEgnkQXHC9i/sYtKJ4ea3WGGpgSJdMpiBlAd0A0ss2M5+wXfxHBkYy+5SlDONq6vOvY1fUly97c6AkRJBODg8G/+m3SC6AcW+ou+o6rpzMI+M4tQbovAP+MAy5YtYKvc4NtTlVgqFiJPUqlk11qsAhvJnXKNyMIED5jTds48PNF/iRQCPKyLLIMU0yqA0WZriDzF7LP+M5eVwWyEvv0/14iwnrG1dIEML7bdNeokTQ41/iM2/wUTSHstnLzBhmVQsqkZV3LXLPM4C6BblRSgHgZlzVuI4EPW2aFnOGwhzF7EovDhj6kGfzur8P/6iw8bFEjOM6FlCC/QPzWwVvF22UWRT2QkSUNF8uI2V9K2NuLCKsv6ehZ3Ab36Aj5RdQZ1pP4faimRwSxtD1/ha8cAbU3v2CteiKsXGCm+ZNmJi0EQX/aPZpJeR2ju1nnRYQCAOQel+344q86JU3T/56QtepAnAN2DnH3neFs4ySc4PoIrxeZeAX3eo37WjYWXUNVcHb3qp7Log6g7gLi14LY37HGbGHBEA6DMMZ4HM1Oe/s2bqSx,iv:NRKlXHsiViFLi4ygP/xO1XFyFC+g1hmsvbrOod86nPc=,tag:8QIoUEwsxrz7SlMFJ5uAzg==,type:str]
sops:
    age:
        - recipient: age1tfhrx9u62qypvelr5padylmf3es8fc5qzlkg4y6qf266637sgs7sem52p9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPckkvM2taNy9QK1N5aS8w
            M08yS0RpSDI0UStObUx6UzhvbTNoOXR2QTBnCktUa0JRekI2YmZRZEYwMlVBdjA3
            RlNiSlFPMmx3SUlQc0pFVFhNMWZjY0kKLS0tIHJEMy84L3puM3RMWkRGMnRiTkc3
            UXJwUkxlNDJUbmYyWnpobncwRElUTzAKOHXqoS63RSxGnQFxGGsvkOJmBOuY+J3w
            H2z3+i1a2YQskCEyIk3DSc8tdHyqlfSYj59ny3Jf+R2ifIf0Wg6bXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T10:50:10Z"
    mac: ENC[AES256_GCM,data:L6TwJRyQ7RlQCyRb1nx6sPk8UDyqBoLIgzxNSs8JbV0dvrA01MUin/Yzi8XhqMy7LbIkglgs5hmVB1S2awUBM6EMhBImAHZJ/ltzOxytN94CUmYOKfDMF7FMQVeCt9gHmzy0Jp2MHzckBF8Z6S+wbCPGREre5P5HqX639mzKNto=,iv:DDxXajw7CIejBA0aGU6B6SgERmss0dgD0Z778d7QUKI=,tag:3jrykZprNWlipSVSpEDmWA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
