apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant
subsets:
  - addresses:
      - ip: 192.168.1.21
    ports:
      - port: 8123
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ha.streamixs.com`)
      kind: Rule
      services:
        - name: homeassistant
          port: 8123
  tls: {}
