crds:
  enabled: true

grafana:
  enabled: true
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      nginx-ingress:
        gnetId: 9614
        revision: 1
        datasource: Prometheus
      argo-rollouts:
        gnetId: 16017
        revision:
        datasource: Prometheus

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}

alertmanager:
  enabled: true