apiVersion: v1
kind: Secret
metadata:
    name: forward-auth-secret
    namespace: auth
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:ff9I9f2KE3MrA0TOP6wz3LaSPyfzm4smMPdfOkMFoxMK5+/e,iv:Jm+klq1V4ypI40TB0qAzLtL4awbp0Jp6lgnBUoOS6j4=,tag:u2cH5wAfnK9rZR2wpm0vHg==,type:str]
    client-secret: ENC[AES256_GCM,data:mvtQUfM7bFLmFZRioTzA8U+bviK5NJShBQ1tDI4Bt2U=,iv:scdrXg8nBJGsNKvrtSXElI+kbm5jGXe0CG7KCS8+GvQ=,tag:e9ytG+Z9rKj6tUiRmj7vJg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:8WtJNeqEgE+SSHww+4JlPmM/PDwfUa33LPOVpX4/8Ug=,iv:hyhdzsW1PQHwLz5TiPOAvcyGIsUjRHz/LVFzGfzNTBI=,tag:PCTV+gWwCBnGv64rpfNYCA==,type:str]
sops:
    age:
        - recipient: age1v5xqeh0yg2qp2adtje8crzrut467mrsjnh4cax7cu8xghrnvm54qg0fyde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTndFUklxMEs3eXhNVEVQ
            MUNvZVUrc2E3NmVqNmJlS2E1NUlmYzkwM253ClU0ZnJ0Q2YwNjRCMHJiK21Jek1V
            K3J1V3FzRUF4VmFYSG5XSHRLTms3Z0EKLS0tIDNFWHRmQktwTmVyeiswb1U0dHVD
            b21MVm5Ka1ZRRmpVL2c4R0VQZkNuS0UKGf2leBOg7bTCdBE6S1xlAhEzz2HVGkNo
            pNT/0xq/ySjbbJt42B6AI0FINd0I1MJM7asIsOeJbPf01G3Ed52sRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T15:54:32Z"
    mac: ENC[AES256_GCM,data:oMql7k2aR95ALnF+Z2O0OeNdhVGnTGMeiTQYUok88Jc5JIB7vf1xZXVhagNsfSIjFvoRUpdtLJc35adGqF5DlxpWkYtq8vVwoWRqQvFA6vqtPRMi5iZWAJBXbN+waMmMsTf/gd+2Sf+w02gXTVDRYG2Z0prV6+gWo2sPrhY4RrQ=,iv:j7mups+7wINeo2PulT1wH2KPeEBa99D0JlabtahZmLg=,tag:TUBsw/MYCnl/zOiV9THZjw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
