apiVersion: v1
kind: Secret
metadata:
    name: forward-auth-secret
    namespace: auth
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:jAzqsbWZSKBb6oYc8INUo1opsVAmQ46/Yo4J2x+LVYqeec60,iv:Jm+klq1V4ypI40TB0qAzLtL4awbp0Jp6lgnBUoOS6j4=,tag:HTScEcOcJWu5rWVuVhdZ8w==,type:str]
    client-secret: ENC[AES256_GCM,data:5Rc7Saiy25sriMw0Kiq6LEPU5L575ZNIqB1zSIVf4Jg=,iv:scdrXg8nBJGsNKvrtSXElI+kbm5jGXe0CG7KCS8+GvQ=,tag:Vn9XvaYm9CkH4lFtUjFPQA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:WNMFKbNYz78hSQrBd616VN00++yw3uMg7YQYAsO43jQ=,iv:hyhdzsW1PQHwLz5TiPOAvcyGIsUjRHz/LVFzGfzNTBI=,tag:V0vfGIPBumbAyHlWPHOz/g==,type:str]
sops:
    age:
        - recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa241Snp6RjVLUWVyeWlM
            a0xwK2JHN01SN290eW0zRWlsUUxEbTc2RFFBCjMvVnJKaFVVRnFWTzdxdVFMckZH
            cWQ4NmdYOTNqK0Y1WjkvVWwwZnFuSGsKLS0tIGtUd29OMld1S2JwMnhOcE9Cb2Fl
            UGw5cXA0b05mbTcrdm9XNDYxRXhDTm8K/8raUwQvT8t8Tzqs6rzzNuGxClFXdsu2
            naCsU3yEEp10DRWZJ8fNNHw9LomniGOHIPjYwAYWl7/pSoyWO35+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T11:35:27Z"
    mac: ENC[AES256_GCM,data:vxCrTIhNaAYKYKQT/x0wY2QjsyOX0GxCB9I4joBs3sNZo1m+D62ag0gKYNQfPm1evgTqktQrV4rojuynXlHx5RZ4fE09v9M2a/6UJ5OZDfWoAOIjx8Yv+2+GOLH87c6QG34HP7CBMyo4sUsLz5v7cq55qClUwGuFwXDMbTX65jU=,iv:MXO/SDtJ+DnOMDcKn7rRIFcGSDsxYPoJM+2x6WikEf4=,tag:0qhTtGN8KrpsqP7Im16tZg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
