apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - wildcard-certificate.yaml

helmCharts:
  - name: traefik
    namespace: traefik
    releaseName: traefik
    repo: https://traefik.github.io/charts
    valuesFile: values.yaml
    version: 40.2.0
    includeCRDs: true
