service:
  type: LoadBalancer

providers:
  kubernetesIngress:
    enabled: false
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

ingressRoute:
  dashboard:
    enabled: false

ports:
  web:
    middlewares:
      - traefik-redirect-https@kubernetescrd
  websecure:
    tls:
      enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true

extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: redirect-https
      namespace: traefik
    spec:
      redirectScheme:
        scheme: https
        permanent: true

  - apiVersion: traefik.io/v1alpha1
    kind: TLSStore
    metadata:
      name: default
      namespace: traefik
    spec:
      defaultCertificate:
        secretName: streamixs-com-staging-tls
