apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker:1.43.1.10611-1e34174b1
          imagePullPolicy: IfNotPresent
          ports:
            - name: plex
              containerPort: 32400
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-secret
                  key: claim-token
                  optional: true
            - name: ADVERTISE_IP
              value: "https://plex.streamixs.com:443"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "4000m"
              memory: "4Gi"
          livenessProbe:
            httpGet:
              path: /identity
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /identity
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /movies
              subPath: movies
            - name: media
              mountPath: /tv
              subPath: tv
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
