apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - plex-config-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

generators:
  - generators/secret-generator.yaml
