nfs:
  server: 54.36.178.170     # <-- your NAS IP/DNS
  path: /export/k8s         # <-- exported NFS path


storageClass:
  create: true
  name: nfs-client
  defaultClass: false       # set true if you want this as cluster default
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    archiveOnDelete: "true"
    pathPattern: "${.PVC.namespace}-${.PVC.name}"