---
- name: Configurer les nœuds Kubernetes (v1.35) sur Ubuntu 22.04
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Mettre à jour les paquets et installer les dépendances
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Ajouter la clé GPG de Kubernetes
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Ajouter le dépôt Kubernetes
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /"
        mode: "0644"
    - name: Installer kubeadm, kubelet et kubectl
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes
        allow_downgrades: yes
        allow_unauthenticated: yes
- name: Initialiser le cluster (masters uniquement)
  hosts: masters
  become: yes
  tasks:
    - name: Initialiser kubeadm
      ansible.builtin.command: >
        kubeadm init
      register: kubeadm_init
      when: "'masters' in group_names"

    - name: Créer le répertoire .kube
      ansible.builtin.file:
        path: "$HOME/.kube"
        state: directory
        mode: 0755
      when: "'masters' in group_names"

    - name: Copier le fichier admin.conf pour kubectl
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "$HOME/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      become: yes
      when: "'masters' in group_names"

    - name: Récupérer la commande de join
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command
      when: "'masters' in group_names"

    - name: Définir une variable globale avec la commande de join
      ansible.builtin.set_fact:
        kubeadm_join_command: "{{ join_command.stdout }}"
      when: "'masters' in group_names"

- name: Rejoindre le cluster (workers uniquement)
  hosts: workers
  become: yes
  tasks:
    - name: Rejoindre le cluster
      ansible.builtin.command: "{{ hostvars['master-01']['kubeadm_join_command'] }}"
      when: hostvars['master-01']['kubeadm_join_command'] is defined
