apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: pocket-id
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:6mcrfLQMEA/LhBDqfvuVL5hAEZKpj3M/bBNINYd2naQJQlDnO6PLBHmWOIZoJb6GXJVrc/gJoMJ7YSZ3LjIDbQ==,iv:tuFqu7ohe8mHbsMs8E28kRvl2/vVlN30K/ffED3A38k=,tag:cQU6Raku/irbs4cB6ZPdwQ==,type:str]
sops:
    age:
        - recipient: age1tfhrx9u62qypvelr5padylmf3es8fc5qzlkg4y6qf266637sgs7sem52p9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmFTVi95aEpKK1RkM01T
            V2pub2VOVm45bVdEMWlzRThpbkJLSVdIaEZ3Ck95bnMwWE5Qc2hIaTBnNWNTRHFN
            MWxTdkd3TzFja29hemdYeVg4UHRabGsKLS0tIGJQWVdUaTVuNlVLYllBSEFkcGE5
            Y2RRemRKUjIyNkExYmVIZWRmd2E4bVEKcVWPPuVYKSbDPqzM2JyRuEzRwuBode6j
            4XI9+yMWz4vYU38TTV0KPkMwNSHyrfD7f7QYJJ7qW2rQuc5V4eCbjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T08:19:26Z"
    mac: ENC[AES256_GCM,data:TCl+dQamXb4kAIdeAMv9jaessRNcx4MrI+ptULgDuoStV/1ZDkHamQo07QWs3MdItcicYBPXHjPOTGD+fUr1p2ns5YEUQyH0PSiUJU5STvdpZulG22o8u3aKHt6zA6XDg8eCsg9lnaTEzkVfNr6+kU0BRLCzdj164+Y1nZ8pU70=,iv:UsIfzrKqGcPHu2poGzyeYdogw5WJDpCUw5kiD/oXpNA=,tag:CokIjpfGSaMUisH7gCa5tg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
