apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - media-pv.yaml
  - media-pvc.yaml
  - radarr-pvc.yaml
  - sonarr-pvc.yaml
  - prowlarr-pvc.yaml
  - qbittorrent-pvc.yaml
  - qbittorrent-seed-pvc.yaml
  - lidarr-pvc.yaml
  - mixarr-pvc.yaml
  - tautulli-pvc.yaml
  - qui-pvc.yaml
