apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - download-pvc.yaml
  - media-pvc.yaml
  - prowlarr-pvc.yaml
  - radarr-pvc.yaml
  - sonarr-pvc.yaml
  - qbittorrent-pvc.yaml