apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-seed-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
