apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client