apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media-automation
  namespace: argocd
spec:
  description: Media automation project
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
