apiVersion: v1
kind: Secret
metadata:
    name: twingate-connector
    namespace: twingate
type: Opaque
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:vEFwxXiwUOM75nei1JJG/B33avSBnfhErhgxzLTCClIQN62w3w+B3cPPFnf1kFNwdAWFZQUGes40UvSdBSBcdFnf86TSXxl5fBknmpJ6DvEyylEEZVhgLO/O0qYkokI2NnyX5OJOSwrWOq5FPYJRYSg/shmRzaCJ8lOWuzUiyPr/NXDJ8Fo7lwWKec7GMJxZo8ILI+RRcX2HegERBnRCtt/5r1bpWll2kFwCYNhQYTH0b8yxaM7fr3QQwS6fDTTT+XJGyLWySMCleMIGGHTlMpH5ECvyYcH/pWxvhi0KF7RW4xwKxyPweQQ7GtQAE3kzxlnI9HFJUP1Jhe61fMty8UbGAfNa5TForLjOzrV0Jtc9XSTXvewH1hWB+7OmToO+1wcSkHeKvUU7kEU6MXGi6N/QRayLS9EQyO3tVIu+9tji8Uo5mKINtl6dMzWj+0J80BO6c+o1gllP606BtOCQNq69SfdwJeb50dfbL2nDMNU5eXxjci94hFXSGg3yrxe3/c4Aw8XUejMJqcHLWIqAb3yhVgUSH/HJ/n6dP+oqJ4e45LB49wU+weyBYZv40MvxMPc2FszBGKYm25GSSlpNTVWVWHSpAeAlxl5EEyWewB9zMd4vPWRo4+yK8ke/MpwO96M=,iv:mH6BAi4PTxbHQgw1S21SjC9I5uuJZhhs6Oa8lm+4a3I=,tag:6oMNnnglKXrdck7KdbA2vg==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:3J93OVASK7T8w5Q7uHjxJWqkn/ce+NHEVurIc1jvmEDYFlEjtCvH+S9JiKNohIO1QARlAbvRsdog7sJoQx3txiUhKQlt9GeRS6+3PL/dBonFeiqErPi5OAlwZnsED952Hu72uFskp6usU7yK3qpbqG0BMNOqEz1aTelE6zMaG7JQu3wIM+M=,iv:3j81y+O1NXC1KtDsTjj+qwuk9bMxrbFbEVehGdDUIVE=,tag:5W7PRzXavU7Huly9yz7PdQ==,type:str]
sops:
    age:
        - recipient: age1tfhrx9u62qypvelr5padylmf3es8fc5qzlkg4y6qf266637sgs7sem52p9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYzZsTGNRMDNDUGJFbExy
            b1NEWWVwTWNteEVPNXZDVnR4b2xkZFNYSURZCnZXaERwWkZ2NzlHNXJLRzFYZWx4
            NXhPRnJNbHVFMTBCNFAyeEFEbEl0YkUKLS0tIEFEK1pWWFhGSW4yOGtWclNVVmVF
            VjdMNExlbVRRejZiV3dPODVWa05SN00KUNH3gBYsLfWpxGuITHcTkF5f6UV+6UFc
            YmH4wFWk+XFLWMRgP0E0xHjju1ObRC3UuHn9u4TC2rvMeW3tJ76oMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-02T12:32:28Z"
    mac: ENC[AES256_GCM,data:4VANCtr4BXidx5kxEfd8X0xiCcjUpwM9v2hkfCIXgFLw5NQH7IReYA0iVCS3fhrKeuorhjbe4cPi6UCjhnBod+95/5y8h6iD7sSVjFLJExh5V7Vmjs3JTm+/4C41O0CF7d54Ln3C5krf4yP/CffMj75Ews8MOTnBPZi6YhVvXkI=,iv:kw2RlpEmEU42KkBQ3HQzWWIyKTfH5LfW3immLhLC3Zw=,tag:q5Ft9TXJz0SV5Wu8E+uCfQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
