apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      # NE PAS forcer runAsUser/Group ici : s6 a besoin de root
      securityContext:
        fsGroup: 1000                   # ok de garder, pas obligatoire
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: prowlarr
          image: ghcr.io/hotio/prowlarr:release
          imagePullPolicy: Always
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Paris"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: prowlarr-pvc
              mountPath: /config
      volumes:
        - name: prowlarr-pvc
          persistentVolumeClaim:
            claimName: prowlarr-pvc
