installCRDs: true
replicaCount: 2
podDisruptionBudget:
  enabled: true
webhook:
  replicaCount: 2
  podDisruptionBudget:
    enabled: true

prometheus:
  enabled: true

extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53

