apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: kube-system
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:2cmzxKi8LpyDWhdqJbEy2HgJcEEbacBWOTv2njKNGsRtMo1ZHIGz4A==,iv:C64pglrkSTfKAd0mrfSXxESdfkXrjZKm7IAG/doRPlo=,tag:z0b9XDjtD+OjEp/whvk2mg==,type:str]
sops:
    age:
        - recipient: age1tfhrx9u62qypvelr5padylmf3es8fc5qzlkg4y6qf266637sgs7sem52p9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYk02Z3ljR1RvTFVIWmh1
            ZEtJTnZIT2FLWjBLWVhkWXJ2YWxJKzFYYzM0CjhvdlNNOTZySHBKTlZVR0JXc3Ar
            eklBU09ESHhyY044N3hFczE3VlhRNXMKLS0tIE9vbHpyT1VEOTRlQmlQeUR1US9J
            T3ErN2NPY3lydFlDK3RaME1KSmQ1ekEK0ZZX7coaZyduao3lA4Aj4ZfYqwM9G5Qz
            ipyH1s08x8JN/XrsTdnRL4ZtH/krjfPMCij+BT8WihbHK9Y58YgAIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T14:10:24Z"
    mac: ENC[AES256_GCM,data:5Xeil4T68ltsOoV1qVAl9N60df9N1RiSrUYmmWr9IQjyBSoDZ4NOP4d5/a1Q5vNLL+tFV/o7wln4qNR6xS26TRb7k1umQyNcmimh4UYCKFnoq7PNgVGWWjCSwPaCakBfSjBohKErlgsavk6v54QUd344DbKfblwbGQnIpVdRlyU=,iv:azzfcIfft5PUwccuHVeeRkukmMFdYvntDahjvpr8Xvg=,tag:I/0SBkKSAsKomLxuukutcQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
