apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: kube-system
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:zkGiOMjjICVIHVBn1TpLqPU+iE3uIBh1I9fC6wRlMY9ZmiFJROgEKQ==,iv:HIGR6FDJ3G53fUltGoCgVsAaRcBGyWC7Oxot/dUo4Yk=,tag:O7ia4P5M7DIMQ+ldGZvA2Q==,type:str]
sops:
    age:
        - recipient: age1tfhrx9u62qypvelr5padylmf3es8fc5qzlkg4y6qf266637sgs7sem52p9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UlNDNzh5QTBlNHI0T1Vw
            cklJVGxHV2xOTlBYQ01scmNHRlY1T0lYS0JnCjhMYlgxRlM3OVV5TmNqdjFtTmxH
            a1BpeHdnSnFacjQrMUxDNVBKQitNL2MKLS0tIERwbCtQeFhmd1dqUnFtWEFYbldD
            ZmUvWU9jd2Zjc3I2QnhqZEF5RXpQdFkKYOTn+t54bC7j5Q5ziXwxrqJnfi9C/DkM
            70GDCcqDGbPd2klSieZ/qv+74Kr/Jf20MwcxXBMLJlsR4YTxGulh3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T22:50:17Z"
    mac: ENC[AES256_GCM,data:/5V9wR4A1jeVAPj805o5kdNnNcmMViZx83LDYx/FRvoa5Wt2j0vVBCY5/vqzWYX2ZIi2YMLHybUKxdbHY39Ms/0dds00Z1ItGRQCoBUASWnuYsYakhc3R6Z4jpFfOyPkul3KS5TgzHiZN7bP2Ry0mK1csaKvht69ukYAcTlRlvE=,iv:cT3mkiKCwkmJU5+7Zx38OePOBxeG03JFBWfCEa4tSxM=,tag:24sublXtFXMFfmPnXEWkjw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
