apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: kube-system
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:ZduT3GRKRRMOMF5mqz1gI7U8c812Mus23L2TKsidqK6j8UzO1y7L+Q==,iv:C64pglrkSTfKAd0mrfSXxESdfkXrjZKm7IAG/doRPlo=,tag:N5C2rLg9O3LWuNYV8kp5mg==,type:str]
sops:
    age:
        - recipient: age1v5xqeh0yg2qp2adtje8crzrut467mrsjnh4cax7cu8xghrnvm54qg0fyde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTEx1bjEzTEJrb1BCdVdk
            cmRTR3dZWmhMTnVmUmZGc3ZteXUrZFF2dEVjCkdVVEtOeE5VQmRFUkxQdHo1eVJG
            SlBmRndjV0diWTlCUS9Cc01nY2k1ZncKLS0tIHBNUi9KTXVVRjNpci9tU29mT1RH
            c2k3c3VNb1VsdjdybWFvdmdIekVaS2sKohtmWqumG31d1U7u573/0WSIeDUUY8Di
            sJEcm1YH6Q2neYpeXZa0TWQFV9wiOVq5Sf3679iL63iZUKGvIqujLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T15:54:32Z"
    mac: ENC[AES256_GCM,data:1Nl6rh7s9eKLlf4wMhngKXhKmk5GXAN3X34AI+Fz5Fw+E2d6z3c6IAlGUqObv2HWs2GIpOcKW1bmk5UXuAFyNCg5QHTXJvUbL511HZC07lIjAR4jZvKETnk4KH0Nzgt7OVH5mxzQOJeQWYrm/VhvmxN+rLDv+Y1VV9+Uo4wWxMU=,iv:OIiQwShKyic3K6Wd7r3nm8FlyfpahXOaBZNZxPESxIg=,tag:pk6+Y3KNOExWHtyWKWXxpw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
