apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: kube-system
type: Opaque
stringData:
  cloudflare-token: "<Cloudflare API token: dash.cloudflare.com > API Tokens > Create Token>"
