apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-seed
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: qbittorrent-seed
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-seed-bt
  namespace: media
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: qbittorrent-seed
  ports:
    - name: bt-tcp
      protocol: TCP
      port: 30882
      targetPort: 30882
      nodePort: 30882
    - name: bt-udp
      protocol: UDP
      port: 30882
      targetPort: 30882
      nodePort: 30882
