apiVersion: v1
kind: Secret
metadata:
    name: securo-secret
    namespace: securo
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:/WVHHWo+5sb2/Drii1liRspaU/XHuaSSLphXmWeB01iKiOy8WFwDL3B0q94BIWVbWnJxNtaqxPEd5gSwmzN5lA==,iv:oM7EChvEhzjQOR7+VPEa0aHWNo8y0AlyZfHbEtsdpQU=,tag:5CKhcWfuifn9q62tW1xIDA==,type:str]
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeWxINGNIalBITnorakM1
            UmxHQmI5QlZiSzlQMGwwQ0VydUxPWE1HQ1VNClhQTkNZZUxqZmdYWVhma3cvRkRC
            RnJtTnZ1YUJjQUZOMlJGb0JqNFlMWTQKLS0tIEdMdnpNeFZTRGJyb3JMYlhMbE4y
            czJ3MTRiMjNualJlQ2k2Zmd1RVVndGcKXMFsxGQsZjBZ3ivg+ieZlJ2KgtkI6fVL
            rNJn1mPXxlQXTt6NysWnZ5R70aCPMbH42Bb8L1m0X/sU77PxyHeURA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
    lastmodified: "2026-08-19T17:41:01Z"
    mac: ENC[AES256_GCM,data:RrguCkPZVa2gbkbDsfc9d4/3MEte2IVqpECIjilwIVoe/FrluecYzpjsgNwyc9W0hDMnrz1KETqlY6RxBpa8fuL/pDppJD6vUj7Rvnrt20l5bZRplLCc3FjObMe/mAc4jhVnFrqlzcodD/cMCOJwNnmUlXmEppNklC9D8KMLHmU=,iv:jPINQKsOFpsf+ef+G1yOxvnTnjwRHNd7dVVlheSc5pc=,tag:MVnLH0a81yDYm30c+UgdmQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
