apiVersion: v1
kind: Secret
metadata:
    name: securo-s3
    namespace: securo
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:dDlGhOVvNNk=,iv:G6m1E9qTcMlnOdzXnweg2BifIFxmfhAulBl07ZdIlOM=,tag:f66+HGNdfd7uH1bQPC71qA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:YNltk+l3giQ=,iv:d9Ke8tZ3awM2lfhyyOoD2x9HgZHSc9ADQ5MxVWxPNQY=,tag:WKVetHnZsSIh5ELtrKM+fQ==,type:str]
sops:
    age:
        - recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc1BXdFhoWWk5RE92VDBT
            WjliVXFvODBMMzh1UitUSFhWRXBxOFIyWXc0CkF3UmhNdEUyZXBwY3pqallvWTNU
            NzJFajFib0Zobmd0RkJUMkhzRGJsQzQKLS0tIDJ3bWlaRFBmNzN6SUhVSEU2bkQ5
            YmlMRXRMNUhGVGtuNUNJTmJ0bHNJSW8Kn649nsPIw7euIZU0yoHBw1sJSc4baMEv
            h+Iuji7mqBN4OUrMLazQ6rN9CGCyj4jRoPcuEOJponkAr/ErVFhXwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T18:11:18Z"
    mac: ENC[AES256_GCM,data:DL2wznWj3FGyqPfoCdFiHDjilEfCpa0y8DWTQoWpG1UZ7Z65sRU7FWlqLG2jyLQ9P4CUBm6mWStqiWvzGyx4CFqQT0xfpiE/w85eMf/Xbhpf146Vo4o4hFoGc7p9e/BMtsrsXkRfNe8YWrB78hi6RjFryTI3a84bEpYxQTUQW+U=,iv:ueRMYpkxSI7QseZzkaOYLMLCJ0Q0wHW0Vv0Y+wByXpY=,tag:DSn+ZRUKYo3BBvLXQaF8LQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
