apiVersion: v1
kind: Secret
metadata:
    name: securo-db-credentials
    namespace: securo
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mnxNDDc9,iv:FHgor/QORczYTJBFb+caDZxpsiN3M4obkB4nCPpP5FM=,tag:PxWsVyG38H+P5Kk0hUeDxA==,type:str]
    password: ENC[AES256_GCM,data:ygCYoUt598Gba6+cEMXqLWegROcVxm6pXuFOpQ5D6Zi4B9Xk6/mVIw==,iv:F6wpWzJgFUmKEvcdAA7DVH1PeY0Ht2GDDjBdYjKvLaE=,tag:PUbKeoSNUHNYdrcNJIGH1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSWdDSGxLbkQrUVE2bTA3
            N2NOOWNXZ2RCRXd4eXFaQXBwbDhpKzkraFZzCk9kQWdhbkhFaFR0dElMRWZrK09K
            ZnpnQXlqV1JndG9ReGxHZk5TMlJHRTgKLS0tIGhOTlEyWVN5MEI5QTAyOVpIT2xs
            RHh2dlhjcXJFYTFiR3ErVGdmd0ppNVkKdsjBO+TaQzQVrRrQnKXWZohfPmzRoL/2
            9j5bPN3UYl3iJbTxxut3V3Wwmu8Wivr3J1J3vq1tekdgbNhunOXu/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
    lastmodified: "2026-08-19T16:09:04Z"
    mac: ENC[AES256_GCM,data:UWQ15RbMFnDwQEc7pbe/oniamZY9DGJU0DcpZ37DeYphY6OPeJ7P0DBjvmcOiEtMY45/7BDh7yio7VxuJ/xzTdpbQBzpqTPsthGYwYQ+7fWmPOs42TykMsuRt0LX1TBQ/Nq4csmKgsZMFYvO7ILIGiPKdftEJ39M6hwCtNY3NFQ=,iv:Hzyh2pr2FgvUTzf6HdEixji/UBA8AFf9vhuLIICanTk=,tag:Jl0p+9mrrONgcRmC8jtgAg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
