apiVersion: v1
kind: Secret
metadata:
    name: securo-secret
    namespace: securo
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:OW/5GqXUcIOpcInwWdejfuYQrLrFagdFP0Wt68EW1wjAMyaI6qu9JeLoe+JrF5g/D1E0Is89WaNDh+B8n50o2g==,iv:Ad3Fe2yccXtp51d5n1Qm0/HJVwMGq5YwYJx7hRJmPec=,tag:+i/G5lfBqnxkl6BxouScJw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:NJ2P76G5BgY96kWZ9YTYn7wjPmPpqmrYQa+bIMqfo0gYT5tYwAEtOQa/oR41ej3TMyuJqa1rTJAjci/vu8rCDzD/gZ4JTbZUXKx06BPsBg1NFBT99u/ws/qAO234,iv:smRxmQBXuB4Ew6Gghes1gKDjXKCVbL1Vkn6ynTBBqQ0=,tag:Dw/cE2GjtfNNZYgGdRNCnA==,type:str]
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYXhXVFJsaTIyR21nV1pn
            V1UrSWk4UytPMzN3QmtoYkZ3d3FxWmpSc2g0ClVLQituU2RJMDdLKzZzTVp5dUJQ
            dUpHNzJXdmVrbk9xNU9aNnpoNzBxZlUKLS0tIFhjMUlqb0RUZ0F2NmpyeFRpVEpM
            aWp1OEs0UmtkYklnYklvWnQyZDJvaWsK0c5DR/DdKAztfLp480NluNQZ4vUJPCsp
            SSFZ/MnJzOk25Lw6tlwVYTqi6ZEv7CwVimqIBpZ90gntSvq/jVVC+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
    lastmodified: "2026-08-19T16:09:04Z"
    mac: ENC[AES256_GCM,data:/1WUtGufpt6kalToy5fbj2xYYpHm37/GimtKdw7NEwKvVWJfC30jChv0qtDwd4Y2yn7KZn7CF6u49rT6fcizY9IwGXWZHgOPJUh6GWZ0l5Ec4kurFgGjM6pd1q2ppLIFpPBihA/NlBHiT+p2Ok1XTSGdb8t18YT+HHknaJ49oK4=,iv:+KOHYhg4DdtEkJOOGUEHJxbfyB+NFtWpk5teYgS3EWA=,tag:sk7UBs1kTN9U1tr5c2qp6w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
