apiVersion: v1
kind: Secret
metadata:
  name: securo-db-credentials
  namespace: securo
type: kubernetes.io/basic-auth
stringData:
  username: "securo"
  password: "<identique au mot de passe de DATABASE_URL>"
