apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: hermes
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:UA2eLIpCC4ytacKkJs59QKsAXl6Zb6GrUJlAxhqtBT18C9iNLhRWmn6FdS2iSQ==,iv:gLLPLGYY48sFLgQXKgBpJcs9+8eLinPvnm3moMs/Yfs=,tag:LefVP7sGFrjBBh8s5DFtPA==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:Ev7UXOhUpHRuYw==,iv:hZJ10qe5uVMFE+Cj3c3DFEHzVurcuFeRRNhnv5hioMU=,tag:7ULS1OTT6ZSVAuilbETmTg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:mD/MeZyjPg==,iv:ZVFxvvUjuZVLzMqqlTpRNvMiZzGOsnvaA/cGkPT4Fh4=,tag:YuzcRr1oBXSVmVioaMkYAA==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:iEK2bC8v8tGqh83NOwe4ReAE9Wc=,iv:IsgOSESfNqplXmxQGYaybHAq+e/TNGskD3lF0Qq+dzc=,tag:DN/l2SW7RluP91lUcsCmGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSWM2NUlPaGZXMXpXM3E0
            V0V6cGNPblZFUGRDNzFoMzNuYTFad0dKb1JrCm4wN05YQ24rOWxRc0l3Q1VXS21k
            R0NkMTFhNEJxaGgxUXNnQWpjSjZLOUUKLS0tIG1BSjhYYi9XeHBUVUliUWQxTXJF
            MnliaEFnNnpvUmJya2hWVjBkMDlySHMKR1XFtlGd01aORF5csHbwZmsWOoyA132F
            yq8fNy56gtVFkCxXMt2eudKreUL3VHst0iX/6AG6MU4QK6R2LRz5GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
    lastmodified: "2026-09-18T18:12:03Z"
    mac: ENC[AES256_GCM,data:5vsKJ5RsINTAZIZCmcB1yVBy+pXJcgppD4vqr4ek8MMxN641yGUGrwB09/AWzAnfnOH6X3vgeL36IEKi1iDdF3GgfFtMuQsGRSoI+IeZl9aNyGOlmRTnyeKh4zfb8KSs1WRgRtvLXb+QLaHLcGvEJ2lLXUd34cbFUq1kEr2oiKM=,iv:4qQQB2nS0wPRnL26B7SqyPwqS2G0RrMWTVLpoGZbH4g=,tag:y0Ub81p27LiIPVlWdedn0w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
