apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixarr
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mixarr
  template:
    metadata:
      labels:
        app: mixarr
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: mixarr
          image: ghcr.io/aquantumofdonuts/mixarr:v2.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: BASE_URL
              value: "https://mixarr.streamixs.com"
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: mixarr-secret
                  key: SESSION_SECRET
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 90
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mixarr-pvc
