apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - managed-config.yaml
  - hermes-pvc.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - policies

generators:
  - generators/secret-generator.yaml
