apiVersion: v1
kind: Secret
metadata:
    name: immich-s3
    namespace: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:jOIF0iCkGwk=,iv:dhOjsV0k0e7bIKBmSoYpANsomkjmVZgCdSlWzEXrZXk=,tag:GJyGmcGx7BKYPw7enebgSg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:lIXqlfUQAuE=,iv:ZEcb1oa1pluCxpndXVb/QJecgVBSAWjCEGYdvtdZsns=,tag:wUnydp+Q5SbjAyMicWBKXw==,type:str]
sops:
    age:
        - recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTFNaTmpSaVRYdlNxUXhn
            U3FKQ3YzWmdtZHllUWRsckVIb3I5Z0c0TEQwCjVQbjFUN08yb1dTN2xIYnVreEJ3
            SjVmU2sySm1MczR6NFpiRFhXU3FWak0KLS0tIGw2Y0tEZ1hYRndTWWtwZ0Ivcm1F
            WXdmdVhjZzEvSkdlMm1RQTZwd2VBbGsKuhjeTTmUzbjibwGGfVo12C0fIc7kWBNL
            mJfe2T8u++yFw+cyIzBFRPWW1TC89Y/Ppu97S1eLTmvoBEYe1s1LHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T18:11:33Z"
    mac: ENC[AES256_GCM,data:wXpnvQeMAx/MPp++v2HTY2Sm55f+u6sfHUaWFHCZMSmxTrKrpD/1Sscl2dDLOOxzNx0H9S6UQV3k3gsrSfuEnOB3mpp8RrzQdQFfzIgs9AH9drB7WSuWuypLcSy6bGWLNjwXojIzWDKmoIZffW6NOiA200Ho3TufzETYO/Dvj4Q=,iv:jSGgLlTkiLTn96I0pwT0fWGOxKSmMCtBirFgfb6tN3g=,tag:l96RB4cVpZqpq/7QJW9PmA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
