apiVersion: v1
kind: Secret
metadata:
    name: mixarr-secret
    namespace: media
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:3vVr7LLoH49EMLen9+Mv3a7bTQ02GU4t7H9BqAZMYzY63h+X8u7RRRrFNgU=,iv:mFd/0WUu5XbUh2/lYKVphF4llSvQSsGMBPjwoLZfxh8=,tag:c77sx6Qi+9Ot60//wAvasg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:1yRVrDb1Di7AGXej3vdYQxbY3faTSlmiqfJtvZRp4x595WJ38FkaF/IM+fp4KGaZ,iv:366CaZbQqeCxWDb78I9t3Mq0BMnl6YmyUDhafRh5Af0=,tag:wH4DyhKNZK8UooHH+jXoiw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:iiy9jBMX8jyBkIWLYrTTTEaGNf7GApunpdpYXq/jrMYbHew9n4mW2LzHqCBucwjQ,iv:PII9e9AOUmuvTHPhFDAIQhxVpT9q5rJRuGCl+KQi4dQ=,tag:PQPAdmut8Qs8Iqq5mmM4kQ==,type:str]
sops:
    age:
        - recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdUxWNW0zK1BBN3JDbGI5
            eDNaYzVodUpPWm9VajlnbmordjJYWWxQTTNrCkhJQ0YrVUNZS2Y4d1NPaGNWTkZx
            REwrcDlOMVloWXBDMXVIRjc1ZDNIZjQKLS0tIFBZbUdMT1FxWUlrOFR2OElFZjEr
            UFVTY214VEw3Wjl6aTFhczZIdjVYZjgKUkAKjSM/+R2DoZyGT7dWl8jHrLI3oQ9X
            ebGoeSXjt2a6ODqKvAeS/ZcgZoSEJUsR6fN/kcfNvHcz+6x6d4lAmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T15:16:09Z"
    mac: ENC[AES256_GCM,data:rWIgMxXxjehz2176gI5IGO5DDb+WzmfvqN76Sda+4iITJ0kp6d93SN+oFMpKdMk6+sXZGiGkvXf0Kd9l98rGu72+0hZLgFIxX/buF32lLJTBIkDKrhFGyUd04MgL9EvlXK6A0GAwiMDyW6klPujP1JcCHJkkh9hPf6A0ewAdxYc=,iv:AXEbruCro1cd2ltlD3HaMdHfjat0dHcEWhp4B2wPqew=,tag:iQ9CPygITbJWfWbdL/D1rA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
