apiVersion: v1
kind: Secret
metadata:
    name: mixarr-secret
    namespace: media
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:fSlFLW7p3+/gFKbqDQ4e5zLwtS1bpn67HPqDm90A8LPFcm2lgFW6DOs0HS/zwiWH2rAOpUq1nw/cS+G0nbBGWQ==,iv:MhicDQeeShhVxkm7MJdLDGi6BGyLVACItKEcGEaMHnQ=,tag:JW1g4BBF9AF234kvrqrMTg==,type:str]
sops:
    age:
        - recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMmloZ2pzckZ4dmlCWjJN
            Tk94a0hqckJyc3hONUdzOTFvOU5seUt5TENRCm4wRWdOT3d6TFVQRU84ck41Tmdl
            OG5hOCtJVWpUOEhIY0lSdXhrYUxraE0KLS0tIHBFOUlqRmFPbUtWQ29meHhYR2RB
            R0hhTGloVGlYZGdIclJ6dFVCU3JBZGcKPH+Rt59FBRY4oKfwJBrS3N7JptPpavH/
            mf5qvLKafa0e+tAgQiiITJjM/3LFM6Ysa6Ii9Wbe9kz9mNx6l5FEPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T13:25:51Z"
    mac: ENC[AES256_GCM,data:R47Aod3WrCH46B1as9L/vGrS2F1Nivu0WJKaCx3QG4Qylb4Tm7UxNl/S4hegbYPUVqrlEGZqKMwZEsuxzvg/a1zr9A40140CxKg7e+0comRgK2ptL0I5Hkg5NZqwSYdg4oAZkQE4/rmvnR0f2Nr0jhwmKXkIr0AkKYmmgB7zc5Y=,iv:LatFaHSlJs7TNuk6DFESPPjShk9kjaE8TRyWybMTusI=,tag:ADbA3g+7Sv6/uvJh9hOuWw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
