apiVersion: v1
kind: Secret
metadata:
    name: mixarr-secret
    namespace: media
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:I7q4Xq971biRITgWRu7gwQDDfirNZ8oCBMQOBYJ8gOz6oDLkNk5hefkkosY=,iv:AXn63u1rom9btW5sXkfc5k8ZlUDxQLPFioGcQAOvMWI=,tag:3HJqTddxLenwI7PQL0lIhA==,type:str]
sops:
    age:
        - recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eFJNUGdya1JGV3FxVCtn
            UjVhVTJCWFVyN2VPSkpHRExOTFBDRktZaVZZClFWVks0a3JIZnA5TnRKVmNqY1o3
            bldvcnlTek9EanVXazhMS3BrSFpOUlEKLS0tIFh6S2RNeE12aFlURzFCdWlUbjE4
            NjVUTmtVUEV4c3VkdjM0V0dqTGNUS3MKPgydQIHnMnx3WXQH9mksyG6Rc1R/qvIG
            GatI6gdsp3wr0LwTkT9dA6n3O/NfMK4RdstvlVvVSeW2U6h9db9Idg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T13:48:55Z"
    mac: ENC[AES256_GCM,data:5pRemB55DEJleJW027zDk1wGHNpzXk92KvMLoXz+jNq0TqXHs+1ria45VaJYVX0fooVzxkk5K0hge0VT74MXebAkCRuU1LXxkerVx0SMweKwt6oYnVa9dL/L3v0eF+Z6ETLKZdvolaO/A6FNUny5lCvTmP8tR11DuNx+UeRfBzI=,iv:l4Gm9euMzRLVqtxbu3VXbsJrvFSACIv4iPTUKFzq8uY=,tag:N6ObPDr+7yO8m5etGHwWrw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
