apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: democratic-csi

resources:
  - ../../base/democratic-csi

helmCharts:
  - name: democratic-csi
    namespace: democratic-csi
    releaseName: truenas-nfs
    repo: https://democratic-csi.github.io/charts/
    valuesFile: values.yaml
    version: 0.14.7
