apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
type: Opaque
stringData:
    claim-token: ENC[AES256_GCM,data:2itHbWKl81Atnh1NTRa4Gk/VCHrGZqA7raw=,iv:6h7B8PwEjPxbKY5jOB3lzezhDFBLwKO/Ki576uwPdLU=,tag:4W46aIX+/uADOxGwHUZ2Cw==,type:str]
sops:
    age:
        - recipient: age1zzjmvz6lyvndk6fgxlnhtd6q4pwfjmjqt65hdzdsfef8x8tdvgxst2pvev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRzY3STFKWWpDdnB6YnJS
            V2N5VURVSy84NG9FTy9qRjFEWHJWQjBwSEhNCjhCaE1yNDhsdVg1a25SSHYzOVBv
            bW5mZmhnd0YwTGJvV1BPRjJURnQwZ28KLS0tIEx4UVZYekRDakhza05IbEt1N2ZJ
            UVFZMmIzdC9HampuZWU0Sk1ZZG81RUEKvY4SWrMXyKbDS2HHjdldbuNG6KTk9Qvs
            Zh9Dq8rMhGzWtNHlVVgfH+IBO2p55vc1v/1sbyC31iZaPSADOEOPug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T12:24:05Z"
    mac: ENC[AES256_GCM,data:UiTVS5zMSTrVWz7JB8VNfacV8I5qdEGW/fbTU3zP+O0LvroEgamnSudBy90pplBzD9pkZS5XxwnbAP2VnD/nBLCqjCcHKv8l6zoZWlXp15bcoJmkKu4/Zc2Un+quCvhS1tZxBs4xdguJRvQh0k3+uD6KGLltsY8m9JhJ9NLlDIQ=,iv:LYAprqbWhldrNdFx2npsmux2Gi5XbtijQqDchAFK1qE=,tag:I6kRqIgDuKsuLoSxClk0QQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
