apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
type: Opaque
stringData:
    claim-token: ENC[AES256_GCM,data:2itHbWKl81Atnh1NTRa4Gk/VCHrGZqA7raw=,iv:6h7B8PwEjPxbKY5jOB3lzezhDFBLwKO/Ki576uwPdLU=,tag:4W46aIX+/uADOxGwHUZ2Cw==,type:str]
sops:
    age:
        - recipient: age1tfhrx9u62qypvelr5padylmf3es8fc5qzlkg4y6qf266637sgs7sem52p9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTjRtY05lNS9jVmlkZnM3
            UUptTXZ1VGpPNEhtbis5cTQrYlpBY2M4QzM0Cm1XQ1l1MndyY1pzUHRrQjhSZmx0
            OXc1OVArb2d6ZUdjK3JFYTU2dmgxazgKLS0tIG1hMzhmR1l3QWdKdEJwMld4UVlK
            RXgweENCT1pUNUIzTWFVRVUrQTBjaHcK8iOD7K8pCQrX1ZHOQkzm6fk++zOLckJS
            u0dbg8AI6rURe7M3+/SWVGlga2DPWkFyAApWEXpJKQxVL8EZ4e0TiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T12:24:05Z"
    mac: ENC[AES256_GCM,data:UiTVS5zMSTrVWz7JB8VNfacV8I5qdEGW/fbTU3zP+O0LvroEgamnSudBy90pplBzD9pkZS5XxwnbAP2VnD/nBLCqjCcHKv8l6zoZWlXp15bcoJmkKu4/Zc2Un+quCvhS1tZxBs4xdguJRvQh0k3+uD6KGLltsY8m9JhJ9NLlDIQ=,iv:LYAprqbWhldrNdFx2npsmux2Gi5XbtijQqDchAFK1qE=,tag:I6kRqIgDuKsuLoSxClk0QQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
