apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
type: Opaque
stringData:
    claim-token: ENC[AES256_GCM,data:v4SEhiysIv4943nleyxCqbQC5oI6DP1e7TM=,iv:6h7B8PwEjPxbKY5jOB3lzezhDFBLwKO/Ki576uwPdLU=,tag:/SECTWRM/aebUV0Xn4Rkow==,type:str]
sops:
    age:
        - recipient: age1v5xqeh0yg2qp2adtje8crzrut467mrsjnh4cax7cu8xghrnvm54qg0fyde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTFRSVm14SDM5eHY5emsy
            MXlSbUlmMktzYW9TV0VXU0VCbUZGaUJNKzM4Ck85KzkwNElvU1ZLcEVvbmc3YkRj
            dktzTG43YWlGak5tMXFWTExRYjZ2b2sKLS0tIEcvY2R3OFVwYWZpMk0zcWtQY1Bk
            aDNOL292L1JtWVZJYktGM21Qb0cydDQKJQShJgGKZcmB1Yg5FsnVe27d8DMMClV7
            AQ5ozjC8ULV1NzVr+rAINqm2brSDyyzWRtuBtwezo+ufsKrlyLkhPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T15:54:32Z"
    mac: ENC[AES256_GCM,data:q8VDETBNKNrnemb6VYMESV6o1BlzpHo91j5b80jjMLfpyIXBQiyaQ8vDo9JiUBjmTdVWwRYLdA9w16TVQw6ReaFKO6Wx6BGx4mKLbpYkOjs0TRhFSqkAviU5U4SpjmRtSUCUaRH8L8/gVrjbQ4ovFUAja9x7naNIrTrHmo6PNjw=,iv:G2xtLPKS2BBcdRkNNStSMh1V7TnFhu+Rx2r8xvGh9EU=,tag:N0IYbQIqrqyxrIiuKbUBhA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
