controllers:
  main:
    containers:
      main:
        image:
          tag: v2.6.3
        env:
          DB_HOSTNAME: immich-db-rw
          DB_PORT: "5432"
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: immich-db-app
                key: username
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-db-app
                key: password
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: immich-db-app
                key: dbname

immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-library-pvc

valkey:
  enabled: true
  persistence:
    data:
      enabled: true
      size: 1Gi
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      storageClass: longhorn

server:
  enabled: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false

machine-learning:
  enabled: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            pullPolicy: IfNotPresent
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      storageClass: longhorn
