apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: infra
spec:
  encryptedData:
    api-token: <SEALED_BASE64>
  template:
    type: Opaque
    metadata:
      name: cloudflare-api-token
      namespace: infra
