apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-vpn-secret
  namespace: media
spec:
  encryptedData:
    VPN_SERVICE_PROVIDER: <SEALED_BASE64>
    WIREGUARD_PRIVATE_KEY: <SEALED_BASE64>
    WIREGUARD_ADDRESSES: <SEALED_BASE64>
    OPENVPN_USER: <SEALED_BASE64>
    OPENVPN_PASSWORD: <SEALED_BASE64>
  template:
    type: Opaque
    metadata:
      name: gluetun-vpn-secret
      namespace: media
